apiVersion: v1
kind: Pod
metadata:
  name: psql-test
  namespace: cloudmart-prod
spec:
  containers:
  - name: psql
    image: postgres:15
    command: ["sleep", "3600"]
    env:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: cloudmart-secrets
          key: DB_PASSWORD
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: cloudmart-secrets
          key: DB_HOST
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: cloudmart-secrets
          key: DB_USER
  restartPolicy: Never
