apiVersion: v1
kind: Pod
metadata:
  name: test-db
  namespace: cloudmart-prod
  labels:
    app: test-db
spec:
  containers:
  - name: test
    image: bitnami/postgresql:15
    command: ["sh", "-c", "PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d cloudmart -c '\\conninfo'"]
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: cloudmart-secrets
          key: DB_PASSWORD
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: cloudmart-secrets
          key: DB_HOST
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: cloudmart-secrets
          key: DB_USER
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      runAsUser: 1001
  restartPolicy: Never
