apiVersion: v1
kind: Secret
metadata:
  name: cloudmart-secrets
  namespace: cloudmart-prod
type: Opaque

stringData:
  JWT_SECRET: noKin8mpP9iMS9jZLt2gdFHApe48oMeL9Wq5LX856rv

  # Production RDS
  DB_HOST: cloudmart-users-db-production.cetoes2w8ujr.us-east-1.rds.amazonaws.com
  DB_USER: cloudmart
  DB_PASSWORD: cloudmartdb#4321

  DB_NAME: cloudmart
  DB_PORT: "5432"
  DB_SSLMODE: require

  SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/537090271991/cloudmart-order-events-production
  AWS_REGION: us-east-1