# k8s/secret-provider-class.yaml
# Allows pods to read secrets from AWS Secrets Manager
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloudmart-db-secret
  namespace: cloudmart-prod
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "cloudmart/prod/db-password"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db-username
          - path: password
            objectAlias: db-password
