# CI replaces AWS_ACCOUNT_ID and ROLE_ENVIRONMENT before applying this file.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service-sa
  namespace: cloudmart-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/cloudmart-ROLE_ENVIRONMENT-product-service-role
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: cloudmart-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/cloudmart-ROLE_ENVIRONMENT-order-service-role
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  namespace: cloudmart-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/cloudmart-ROLE_ENVIRONMENT-notification-service-role
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: cloudmart-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/cloudmart-ROLE_ENVIRONMENT-user-service-role
automountServiceAccountToken: true
