# k8s/service-accounts.yaml
# Links each Kubernetes service to its AWS IAM role

apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service-sa
  namespace: cloudmart-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::537090271991:role/cloudmart-product-service-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: cloudmart-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::537090271991:role/cloudmart-order-service-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  namespace: cloudmart-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::537090271991:role/cloudmart-notification-service-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: cloudmart-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::537090271991:role/cloudmart-user-service-role
